#!/usr/bin/env bash
# Unified InferenceBazaar contract deploy: InferenceBazaarSettlement + InferenceBazaarBSM (timelock-owned,
# initial book registered), then capture the deployed addresses into
# deploy/.env.deployed and the blueprint manifest. The SAME script runs against
# local anvil OR Base Sepolia — only the RPC + production env change. The blueprint
# registration (cargo tangle) runs after this, in base-sepolia.sh.
#
#   # local (anvil): MockUSD token, deployer is the timelock admin
#   RPC=http://127.0.0.1:8545 PRIVATE_KEY=0xac09… deploy/deploy-inference-bazaar.sh
#
#   # Base Sepolia: real USDC, a Gnosis Safe as the timelock admin
#   RPC=https://sepolia.base.org PRIVATE_KEY=0x<funded> PAYMENT_TOKEN=0x<USDC> \
#     TIMELOCK_ADMIN=0x<safe> deploy/deploy-inference-bazaar.sh
#
#   # dry run (no broadcast):  BROADCAST="" RPC=… PRIVATE_KEY=… deploy/deploy-inference-bazaar.sh
set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

RPC="${RPC:-http://127.0.0.1:8545}"
: "${PRIVATE_KEY:?set PRIVATE_KEY (funded deployer)}"
export PRIVATE_KEY
export USE_TIMELOCK="${USE_TIMELOCK:-1}"
export TIMELOCK_DELAY="${TIMELOCK_DELAY:-86400}"
export TIMELOCK_ADMIN="${TIMELOCK_ADMIN:-$(cast wallet address --private-key "$PRIVATE_KEY")}"
export REGISTER_BOOK="${REGISTER_BOOK:-1}"
# PAYMENT_TOKEN unset => Deploy.s.sol deploys MockUSD (local/dev). Set real USDC on testnet.
[ -n "${PAYMENT_TOKEN:-}" ] && export PAYMENT_TOKEN
# Optional SP1 proven path: export SP1_VERIFIER + SP1_VKEY to wire it at deploy.
BROADCAST="${BROADCAST---broadcast}" # unset => broadcast; set empty => dry run
ENV_OUT="${DEPLOY_ENV_OUT:-deploy/.env.deployed}"
DEF="${BLUEPRINT_DEF:-blueprint.toml}"

echo "==> Deploying InferenceBazaar contracts to $RPC (timelock=$USE_TIMELOCK admin=$TIMELOCK_ADMIN book=$REGISTER_BOOK)"
OUT=$(cd contracts && FOUNDRY_DISABLE_NIGHTLY_WARNING=1 forge script script/Deploy.s.sol \
  --rpc-url "$RPC" $BROADCAST 2>&1) || { echo "$OUT" | tail -30; exit 1; }
echo "$OUT" | grep -E "MockUSD:|InferenceBazaarSettlement:|InferenceBazaarBSM:|book registered:|TimelockController:|SP1 verifier wired" || true

SETTLEMENT=$(grep -oP 'InferenceBazaarSettlement: \K0x\w+' <<<"$OUT" || true)
BSM=$(grep -oP 'InferenceBazaarBSM: \K0x\w+' <<<"$OUT" || true)
PAYTOKEN="${PAYMENT_TOKEN:-$(grep -oP 'MockUSD: \K0x\w+' <<<"$OUT" || true)}"
[[ -n "$SETTLEMENT" && -n "$BSM" ]] || { echo "could not parse deployed addresses"; echo "$OUT" | tail -30; exit 1; }

CHAIN_ID=$(cast chain-id --rpc-url "$RPC" 2>/dev/null || echo "")
cat > "$ENV_OUT" <<EOF2
# Generated by deploy/deploy-inference-bazaar.sh against $RPC — source into operators + app.
INFERENCE_BAZAAR_CHAIN_ID=$CHAIN_ID
INFERENCE_BAZAAR_SETTLEMENT_ADDR=$SETTLEMENT
INFERENCE_BAZAAR_BSM_ADDR=$BSM
INFERENCE_BAZAAR_PAYMENT_TOKEN=$PAYTOKEN
INFERENCE_BAZAAR_RPC_URL=$RPC
EOF2
echo "==> wrote $ENV_OUT"

# Wire the settlement address into the blueprint manifest (best-effort, in place).
if [[ -f "$DEF" ]] && grep -q "inference_bazaar_settlement_address" "$DEF"; then
  python3 - "$DEF" "$SETTLEMENT" <<'PY'
import re, sys
p, addr = sys.argv[1], sys.argv[2]
s = open(p).read()
s = re.sub(r'inference_bazaar_settlement_address = ".*?"', f'inference_bazaar_settlement_address = "{addr}"', s)
open(p, "w").write(s)
PY
  echo "==> set inference_bazaar_settlement_address=$SETTLEMENT in $DEF"
fi

echo "==> Contracts ready: settlement=$SETTLEMENT bsm=$BSM token=$PAYTOKEN chain=$CHAIN_ID"
