#!/usr/bin/env bash
# Onboard an Inference Bazaar bonded issuer: the mechanical steps in
# docs/OPERATOR_ONBOARDING.md, in order — check deps, build the operator,
# (optionally) mint a key, (optionally) post collateral, and write a ready-to-run
# operator .env. The Tangle service registration/approval is governance
# (multi-party) and is printed as the next step, not auto-run.
#
# Usage (all via env):
#   # use an existing deployment + your own key, just build + write .env:
#   source deploy/.env.deployed
#   OPERATOR_KEY=0x... INFERENCE_BAZAAR_INFERENCE_URL=https://… deploy/onboard-operator.sh
#
#   # also post 20 tsUSD of collateral in the same run:
#   COLLATERAL_AMOUNT=20000000 deploy/onboard-operator.sh
#
#   # generate a fresh operator key (prints the address to fund):
#   GENERATE_KEY=1 deploy/onboard-operator.sh
set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

say() { printf '\033[1;35m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# ── 0. deps ──────────────────────────────────────────────────────────────────
command -v cargo >/dev/null || die "cargo not found (install Rust)"
command -v cast  >/dev/null || die "cast not found (install Foundry)"

# ── 1. chain coordinates ─────────────────────────────────────────────────────
# Prefer an explicit env; fall back to a prior contract deploy.
if [[ -z "${INFERENCE_BAZAAR_SETTLEMENT_ADDR:-}" && -f deploy/.env.deployed ]]; then
  say "sourcing deploy/.env.deployed"
  # shellcheck disable=SC1091
  source deploy/.env.deployed
fi
: "${INFERENCE_BAZAAR_SETTLEMENT_ADDR:?set INFERENCE_BAZAAR_SETTLEMENT_ADDR (or run deploy/deploy-inference-bazaar.sh first)}"
: "${INFERENCE_BAZAAR_RPC_URL:?set INFERENCE_BAZAAR_RPC_URL}"
: "${INFERENCE_BAZAAR_CHAIN_ID:?set INFERENCE_BAZAAR_CHAIN_ID}"

# ── 2. build the operator ────────────────────────────────────────────────────
say "building inference-bazaar-operator (--features blueprint)"
cargo build --release -p inference-bazaar-operator --bin inference-bazaar-operator --features blueprint

# ── 3. key ───────────────────────────────────────────────────────────────────
if [[ "${GENERATE_KEY:-0}" == "1" && -z "${OPERATOR_KEY:-}" ]]; then
  say "generating a fresh operator key"
  NEW=$(cast wallet new)
  OPERATOR_KEY=$(grep -oiE 'private key:\s*0x[0-9a-f]+' <<<"$NEW" | grep -oiE '0x[0-9a-f]+')
  ADDR=$(grep -oiE 'address:\s*0x[0-9a-f]+' <<<"$NEW" | grep -oiE '0x[0-9a-f]+')
  say "operator address: $ADDR  — FUND THIS WITH GAS + COLLATERAL TOKEN, then re-run with COLLATERAL_AMOUNT"
fi
: "${OPERATOR_KEY:?set OPERATOR_KEY (0x-hex) or pass GENERATE_KEY=1}"
SUBMITTER_KEY="${SUBMITTER_KEY:-$OPERATOR_KEY}"
OPERATOR_ADDR=$(cast wallet address --private-key "$OPERATOR_KEY")
say "operator address: $OPERATOR_ADDR"

# ── 4. collateral (optional, real on-chain txs) ──────────────────────────────
if [[ -n "${COLLATERAL_AMOUNT:-}" ]]; then
  TOKEN="${INFERENCE_BAZAAR_PAYMENT_TOKEN:?set INFERENCE_BAZAAR_PAYMENT_TOKEN to post collateral}"
  say "approving $COLLATERAL_AMOUNT of $TOKEN to settlement"
  cast send "$TOKEN" "approve(address,uint256)" "$INFERENCE_BAZAAR_SETTLEMENT_ADDR" "$COLLATERAL_AMOUNT" \
    --rpc-url "$INFERENCE_BAZAAR_RPC_URL" --private-key "$SUBMITTER_KEY" >/dev/null
  say "depositCollateral($COLLATERAL_AMOUNT)"
  cast send "$INFERENCE_BAZAAR_SETTLEMENT_ADDR" "depositCollateral(uint256)" "$COLLATERAL_AMOUNT" \
    --rpc-url "$INFERENCE_BAZAAR_RPC_URL" --private-key "$SUBMITTER_KEY" >/dev/null
  FREE=$(cast call "$INFERENCE_BAZAAR_SETTLEMENT_ADDR" "freeCollateral(address)(uint256)" "$OPERATOR_ADDR" \
    --rpc-url "$INFERENCE_BAZAAR_RPC_URL" 2>/dev/null || echo "?")
  say "freeCollateral now: $FREE"
fi

# ── 5. write the operator .env ───────────────────────────────────────────────
ENV_OUT="${ENV_OUT:-.env.operator}"
say "writing $ENV_OUT"
cat > "$ENV_OUT" <<EOF
# Generated by deploy/onboard-operator.sh — source before running the operator.
INFERENCE_BAZAAR_CHAIN_ID=$INFERENCE_BAZAAR_CHAIN_ID
INFERENCE_BAZAAR_SETTLEMENT_ADDR=$INFERENCE_BAZAAR_SETTLEMENT_ADDR
INFERENCE_BAZAAR_RPC_URL=$INFERENCE_BAZAAR_RPC_URL
INFERENCE_BAZAAR_FROM_BLOCK=${INFERENCE_BAZAAR_FROM_BLOCK:-0}
INFERENCE_BAZAAR_OPERATOR_KEY=$OPERATOR_KEY
INFERENCE_BAZAAR_SUBMITTER_KEY=$SUBMITTER_KEY
INFERENCE_BAZAAR_INSTRUMENT=${INFERENCE_BAZAAR_INSTRUMENT:-groq/llama-3.1-8b-instant:output}
INFERENCE_BAZAAR_MM_SIZE=${INFERENCE_BAZAAR_MM_SIZE:-50000}
INFERENCE_BAZAAR_OPERATOR_ADDR=${INFERENCE_BAZAAR_OPERATOR_ADDR:-127.0.0.1:9100}
INFERENCE_BAZAAR_SIDECAR_URL=${INFERENCE_BAZAAR_SIDECAR_URL:-http://127.0.0.1:9110}
INFERENCE_BAZAAR_ROUTER_URL=${INFERENCE_BAZAAR_ROUTER_URL:-https://router.tangle.tools}
EOF
# Carry whichever inference backend was configured.
if [[ -n "${INFERENCE_BAZAAR_VLLM_MODEL:-}" ]]; then
  echo "INFERENCE_BAZAAR_VLLM_MODEL=$INFERENCE_BAZAAR_VLLM_MODEL" >> "$ENV_OUT"
elif [[ -n "${INFERENCE_BAZAAR_INFERENCE_URL:-}" ]]; then
  echo "INFERENCE_BAZAAR_INFERENCE_URL=$INFERENCE_BAZAAR_INFERENCE_URL" >> "$ENV_OUT"
  [[ -n "${INFERENCE_BAZAAR_INFERENCE_API_KEY:-}" ]] && echo "INFERENCE_BAZAAR_INFERENCE_API_KEY=$INFERENCE_BAZAAR_INFERENCE_API_KEY" >> "$ENV_OUT"
else
  say "WARNING: no inference backend set (INFERENCE_BAZAAR_VLLM_MODEL or _INFERENCE_URL). A bonded issuer will refuse to boot — add one to $ENV_OUT."
fi

# ── 6. next steps ────────────────────────────────────────────────────────────
cat <<EOF

$(say "done — operator env written to $ENV_OUT")

Next:
  1. Start the market-making sidecar (the pricing brain):
       pnpm --filter @inference-bazaar/mm-sidecar build && node packages/mm-sidecar/dist/index.mjs
  2. Run the operator:
       set -a; source $ENV_OUT; set +a
       cargo run --release -p inference-bazaar-operator --bin inference-bazaar-operator-lite
     (or the blueprint runner: --bin inference-bazaar-operator --features blueprint -- run)
  3. Quote: curl -X POST http://127.0.0.1:9100/mm-tick -H 'content-type: application/json' \\
       -d '{"instrumentId":"${INFERENCE_BAZAAR_INSTRUMENT:-groq/llama-3.1-8b-instant:output}"}'

To join the on-chain blueprint service (governance, multi-party), see
docs/OPERATOR_ONBOARDING.md §8 — register, request-service, get approved.
EOF
